import {Lib, LinkableString} from "./lib";

// the data powering the chart
// please keep in the same order as Discord's docs (https://discord.dev/topics/community-resources#libraries-discord-libraries):
// sort language alphabetically and then name alphabetically

export const libs: Lib[] = [
	{
		name: 'CocApi',
		url: 'https://github.com/devhl-labs/CocApi',
		language: 'C#',
		loginWithToken: 'Yes',
		loginWithEmail: 'Yes',
		dynamicIP: 'No',
		troopInformation: 'Yes',
		events: 'Yes',
		clans_CurrentWar_Leaguegroup: 'Yes',
		clans_clannwarleagues_wars: 'Yes',
		clans_warlog: 'Yes',
		clan_search: 'Yes',
		clans_current_war: 'Yes',
		clans: 'Yes',
		clans_members: 'Yes',
		players: 'Yes',
		players_verify: 'Yes',
		leagues: 'Yes',
		leagues_season_ranking: 'Yes',
		league_info: 'Yes',
		leagues_seasons: 'Yes',
		warleagues: 'Yes',
		warleague_info: 'Yes',
		locations_rankings_clans: 'Yes',
		locations_rankings_players: 'Yes',
		locations_rankings_clan_versus: 'Yes',
		locations_rankings_player_versus: 'Yes',
		locations: 'Yes',
		location_info: 'Yes',
		goldpass: 'Yes',
		labels_player: 'Yes',
		labels_clan: 'Yes',
		note: ''
	},
	{
		name: 'clash.js',
		url: 'https://github.com/ryansyn/clash.js',
		language: 'JavaScript',
		loginWithToken: 'Yes',
		loginWithEmail: 'Yes',
		dynamicIP: 'Yes',
		troopInformation: 'No',
		events: 'No',
		clans_CurrentWar_Leaguegroup: 'Yes',
		clans_clannwarleagues_wars: 'Yes',
		clans_warlog: 'Yes',
		clan_search: 'Yes',
		clans_current_war: 'Yes',
		clans: 'Yes',
		clans_members: 'Yes',
		players: 'Yes',
		players_verify: 'Yes',
		leagues: 'Yes',
		leagues_season_ranking: 'Yes',
		league_info: 'Yes',
		leagues_seasons: 'Yes',
		warleagues: 'Yes',
		warleague_info: 'Yes',
		locations_rankings_clans: 'Yes',
		locations_rankings_players: 'Yes',
		locations_rankings_clan_versus: 'Yes',
		locations_rankings_player_versus: 'Yes',
		locations: 'Yes',
		location_info: 'Yes',
		goldpass: 'Yes',
		labels_player: 'Yes',
		labels_clan: 'Yes',
		note: ''
	},
	{
		name: 'clashofclans.js',
		url: 'https://github.com/clashperk/clashofclans.js',
		language: 'JavaScript',
		loginWithToken: 'Yes',
		loginWithEmail: 'Yes',
		dynamicIP: 'No',
		troopInformation: 'Yes',
		events: 'Yes',
		clans_CurrentWar_Leaguegroup: 'Yes',
		clans_clannwarleagues_wars: 'Yes',
		clans_warlog: 'Yes',
		clan_search: 'Yes',
		clans_current_war: 'Yes',
		clans: 'Yes',
		clans_members: 'Yes',
		players: 'Yes',
		players_verify: 'Yes',
		leagues: 'Yes',
		leagues_season_ranking: 'Yes',
		league_info: 'Yes',
		leagues_seasons: 'Yes',
		warleagues: 'Yes',
		warleague_info: 'Yes',
		locations_rankings_clans: 'Yes',
		locations_rankings_players: 'Yes',
		locations_rankings_clan_versus: 'Yes',
		locations_rankings_player_versus: 'Yes',
		locations: 'Yes',
		location_info: 'Yes',
		goldpass: 'Yes',
		labels_player: 'Yes',
		labels_clan: 'Yes',
		note: 'TypeScript Support'
	},
	{
		name: 'coc.py',
		url: 'https://github.com/mathsman5133/coc.py',
		language: 'Python',
		loginWithToken: 'Yes',
		loginWithEmail: 'Yes',
		dynamicIP: 'Yes',
		troopInformation: 'Yes',
		events: 'Yes',
		clans_CurrentWar_Leaguegroup: 'Yes',
		clans_clannwarleagues_wars: 'Yes',
		clans_warlog: 'Yes',
		clan_search: 'Yes',
		clans_current_war: 'Yes',
		clans: 'Yes',
		clans_members: 'Yes',
		players: 'Yes',
		players_verify: 'Yes',
		leagues: 'Yes',
		leagues_season_ranking: 'Yes',
		league_info: 'Yes',
		leagues_seasons: 'Yes',
		warleagues: 'Yes',
		warleague_info: 'Yes',
		locations_rankings_clans: 'Yes',
		locations_rankings_players: 'Yes',
		locations_rankings_clan_versus: 'Yes',
		locations_rankings_player_versus: 'Yes',
		locations: 'Yes',
		location_info: 'Yes',
		goldpass: 'Yes',
		labels_player: 'Yes',
		labels_clan: 'Yes',
		note: ''
	},
	{
		name: 'cocRb',
		url: 'https://github.com/Crusader500/cocRb',
		language: 'Ruby',
		loginWithToken: 'Yes',
		loginWithEmail: 'Yes',
		dynamicIP: 'No',
		troopInformation: 'Yes',
		events: 'Yes',
		clans_CurrentWar_Leaguegroup: 'Yes',
		clans_clannwarleagues_wars: 'Yes',
		clans_warlog: 'Yes',
		clan_search: 'Yes',
		clans_current_war: 'Yes',
		clans: 'Yes',
		clans_members: 'Yes',
		players: 'Yes',
		players_verify: 'Yes',
		leagues: 'Yes',
		leagues_season_ranking: 'Yes',
		league_info: 'Yes',
		leagues_seasons: 'Yes',
		warleagues: 'Yes',
		warleague_info: 'Yes',
		locations_rankings_clans: 'Yes',
		locations_rankings_players: 'Yes',
		locations_rankings_clan_versus: 'Yes',
		locations_rankings_player_versus: 'Yes',
		locations: 'Yes',
		location_info: 'Yes',
		goldpass: 'Yes',
		labels_player: 'Yes',
		labels_clan: 'Yes',
		note: ''
	}
]
